# Values for kafka-ui helm chart
# repo: https://provectus.github.io/kafka-ui-charts

yamlApplicationConfig:
  kafka:
    clusters:
      - name: pr-cluster
        bootstrapServers: 192.168.30.24:9092,192.168.30.25:9092,192.168.30.26:9092,192.168.30.27:9092
        # zookeeper: zookeeper:2181
      - name: np-cluster
        bootstrapServers: 192.168.20.21:9092,192.168.20.22:9092,192.168.20.23:9092
    # properties:
    #   security.protocol: PLAINTEXT

ingress:
  enabled: false
  host: kafkaui.k8spr.area51
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
